Adds a fix for command-not-found and fixes an issue on 6.2.7
alivx/CIS-Ubuntu-20.04-Ansible pull request #81
Opened 2022-04-28 15:55 UTC by Sebastian-RG

There exists an issue with command-not-found crashing when umask is set to 027.
https://bugs.launchpad.net/command-not-found/+bug/1824000/
This PR implements a permanent fix for it. It is only enabled if `fix_command_not_found` is true (false by default)

This PR also corrects an issue in 6.2.7 where the variable `output_6_2_7` is wrongly overwritten if `fix_dot_include_folders` is false.

2022-05-01 14:41 UTC, alivx commented
@jvleminc  could you please check this PR

2022-05-03 14:44 UTC, jvleminc requested changes

2022-05-04 12:11 UTC, Sebastian-RG commented on tasks/section_5_Access_Authentication_and_Authorization.yaml
> +      when: fix_command_not_found
The issue does not appear until an `apt-get update` or `apt update` command is ran. This also is not under the CIS recommendations and so I believe while it is a very convenient option, it should not be enabled by default. The average user will not expect this as the default behavior of the script.

2022-05-04 12:11 UTC, Sebastian-RG commented on defaults/main.yml
> +fix_command_not_found: false # Adds a change to /etc/apt/apt.conf.d/50command-not-found to fix a known issue.
Added

2022-05-04 13:29 UTC, jvleminc approved these changes

2022-05-04 13:30 UTC, merged